In [5]:
from numpy import *
from pandas import *
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [6]:
# 1.3.1

print(array([[0, 1] * 4, [1, 0] * 4] * 4))

<NumpyExtensionArray>
[[0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0]]
Length: 8, dtype: object


In [7]:
# 1.3.2

print(*[f"\n{i}" for i in [list(arange(5)) for _ in range(5)]])



[0, 1, 2, 3, 4] 
[0, 1, 2, 3, 4] 
[0, 1, 2, 3, 4] 
[0, 1, 2, 3, 4] 
[0, 1, 2, 3, 4]


In [8]:
# 1.3.3

print(random.rand(3, 3, 3))

[[[0.62048315 0.86595129 0.31501986]
  [0.95137511 0.04232712 0.67233313]
  [0.54891612 0.3791767  0.44650086]]

 [[0.43583815 0.244001   0.06437712]
  [0.81993056 0.68572503 0.84703247]
  [0.22840812 0.95866495 0.19701248]]

 [[0.66966675 0.31957544 0.4390022 ]
  [0.80879049 0.59631452 0.14313569]
  [0.77312188 0.05700333 0.1980804 ]]]


In [9]:
# 1.3.4

print(*[f"\n{k}" for k in [[0 if all([i > 0, i < len(arr) - 1, j > 0, j < len(arr) - 1]) else 1 for i in range(len(arr))] for j in range(len(arr))]]) if (any(arr := ones((5, 5), dtype=int))) else print("")



[1, 1, 1, 1, 1] 
[1, 0, 0, 0, 1] 
[1, 0, 0, 0, 1] 
[1, 0, 0, 0, 1] 
[1, 1, 1, 1, 1]


In [10]:
# 1.3.5

print(*sort(random.rand(10))[::-1])


0.9128078333222305 0.8958947158759388 0.7946946813077139 0.5554179673933236 0.5503684563000055 0.39059234406214094 0.3541676202402786 0.14052152186957734 0.12904598990279748 0.00923272934096142


In [11]:
# 1.3.6

print(arr := arange(30).reshape(5, 6), "\n", arr.shape, arr.size, arr.ndim)



[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] 
 (5, 6) 30 2


In [12]:
# 2.3.1

print((((a := Series([0, 0], ['x', 'y']))['x'] - (b := Series([1, 1], ['x', 'y']))['x'])**2 + (a['y'] - b['y']) ** 2) ** 0.5)

1.4142135623730951


In [13]:
# 2.3.2

(df := read_csv("https://query1.finance.yahoo.com/v7/finance/download/AAPL?period1=1632575268&period2=1664111268&interval=1d&events=history&includeAdjustedClose=true")).head()

Date        Open        High         Low       Close   Adj Close  \
0  2021-09-27  145.470001  145.960007  143.820007  145.369995  143.707397   
1  2021-09-28  143.250000  144.750000  141.690002  141.910004  140.286972   
2  2021-09-29  142.470001  144.449997  142.029999  142.830002  141.196472   
3  2021-09-30  143.660004  144.380005  141.279999  141.500000  139.881683   
4  2021-10-01  141.899994  142.919998  139.110001  142.649994  141.018509   

      Volume  
0   74150700  
1  108972300  
2   74602000  
3   89056700  
4   94639600

In [14]:
# 2.3.3

display(df.head(3), df.tail(3), df.shape, df.describe(), df.iloc[1:3], df[df["Open"] >= 180])


Date        Open        High         Low       Close   Adj Close  \
0  2021-09-27  145.470001  145.960007  143.820007  145.369995  143.707397   
1  2021-09-28  143.250000  144.750000  141.690002  141.910004  140.286972   
2  2021-09-29  142.470001  144.449997  142.029999  142.830002  141.196472   

      Volume  
0   74150700  
1  108972300  
2   74602000

Date        Open        High         Low       Close   Adj Close  \
248  2022-09-21  157.339996  158.740005  153.600006  153.720001  152.813461   
249  2022-09-22  152.380005  154.470001  150.910004  152.740005  151.839233   
250  2022-09-23  151.190002  151.470001  148.559998  150.429993  149.542847   

        Volume  
248  101696800  
249   86652500  
250   96029900

(251, 7)

Open        High         Low       Close   Adj Close  \
count  251.000000  251.000000  251.000000  251.000000  251.000000   
mean   158.428446  160.493387  156.568008  158.618048  157.251717   
std     12.505458   12.458429   12.381958   12.401045   12.270436   
min    130.070007  132.389999  129.039993  130.059998  129.113632   
25%    148.754998  149.904998  147.470001  148.845001  147.582581   
50%    159.589996  162.139999  156.720001  159.300003  157.972855   
75%    169.385002  171.065002  167.300003  169.060005  167.774925   
max    182.630005  182.940002  179.119995  182.009995  180.190964   

             Volume  
count  2.510000e+02  
mean   8.871277e+07  
std    2.625930e+07  
min    4.100000e+07  
25%    7.018920e+07  
50%    8.347440e+07  
75%    1.003336e+08  
max    1.954327e+08

Date        Open        High         Low       Close   Adj Close  \
1  2021-09-28  143.250000  144.750000  141.690002  141.910004  140.286972   
2  2021-09-29  142.470001  144.449997  142.029999  142.830002  141.196472   

      Volume  
1  108972300  
2   74602000

Date        Open        High         Low       Close   Adj Close  \
54  2021-12-13  181.119995  182.130005  175.529999  175.740005  173.983643   
64  2021-12-28  180.160004  181.330002  178.529999  179.289993  177.498154   
69  2022-01-04  182.630005  182.940002  179.119995  179.699997  177.904053   

       Volume  
54  153237000  
64   79144300  
69   99310400

In [15]:
# 3.3.2

display((arr := read_csv("https://raw.githubusercontent.com/akmand/datasets/master/iris.csv")).head(5))

arr[['sepal_length_cm']] = MinMaxScaler().fit_transform(arr[['sepal_length_cm']])
arr[['sepal_width_cm']] = StandardScaler().fit_transform(arr[['sepal_length_cm']])

arr.head(5)


sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222       -0.900681              1.4             0.2  setosa
1         0.166667       -1.143017              1.4             0.2  setosa
2         0.111111       -1.385353              1.3             0.2  setosa
3         0.083333       -1.506521              1.5             0.2  setosa
4         0.194444       -1.021849              1.4             0.2  setosa