In [5]:
from numpy import *
from pandas import *
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [4]:
# 1.3.1

print(array([[0, 1] * 4, [1, 0] * 4] * 4))

<NumpyExtensionArray>
[[0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0], [0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1], [1, 0, 1, 0, 1, 0, 1, 0]]
Length: 8, dtype: object


In [36]:
# 1.3.2

arr = [arange(5) for _ in arange(5)]
print(*arr, sep="\n")

[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]


In [6]:
# 1.3.3

print(random.rand(3, 3, 3))

[[[0.96367673 0.14389776 0.5383308 ]
  [0.21666765 0.07210988 0.82150481]
  [0.6153608  0.20833959 0.59144639]]

 [[0.22031917 0.71333007 0.07754624]
  [0.34006633 0.70626561 0.41099123]
  [0.3604581  0.0287777  0.97326697]]

 [[0.43444301 0.17028387 0.44819215]
  [0.74544479 0.91731535 0.88331339]
  [0.75475489 0.61946799 0.4914747 ]]]


In [37]:
# 1.3.4
n, m = 5, 5
arr = [k for k in [[+(not (0 < i < m - 1 and 0 < j < n - 1)) for i in arange(m)] for j in arange(n)]]
print(*arr, sep='\n')


[1, 1, 1, 1, 1]
[1, 0, 0, 0, 1]
[1, 0, 0, 0, 1]
[1, 0, 0, 0, 1]
[1, 1, 1, 1, 1]


In [15]:
# 1.3.5

print(*sort(random.rand(10)))


0.1742863731435249 0.22157042125061654 0.2509868671035832 0.26666901858995173 0.2957048337862491 0.44203437687564984 0.6433498013979186 0.673068074014822 0.715297116469351 0.8005168795529402


In [5]:
# 1.3.6
arr = arange(30).reshape(5, 6)
print(arr)
print(arr.shape, arr.size, arr.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
(5, 6) 30 2


In [6]:
# 2.3.1
a = Series([0, 0], ['x', 'y'])
b = Series([1, 1], ['x', 'y'])
print(((a['x'] - b['x'])**2 + (a['y'] - b['y']) ** 2) ** 0.5)

1.4142135623730951


In [11]:
# 2.3.2

(df := read_csv("https://query1.finance.yahoo.com/v7/finance/download/AAPL?period1=1632575268&period2=1664111268&interval=1d&events=history&includeAdjustedClose=true")).head()

Date        Open        High         Low       Close   Adj Close  \
0  2021-09-27  145.470001  145.960007  143.820007  145.369995  143.707428   
1  2021-09-28  143.250000  144.750000  141.690002  141.910004  140.287018   
2  2021-09-29  142.470001  144.449997  142.029999  142.830002  141.196457   
3  2021-09-30  143.660004  144.380005  141.279999  141.500000  139.881699   
4  2021-10-01  141.899994  142.919998  139.110001  142.649994  141.018509   

      Volume  
0   74150700  
1  108972300  
2   74602000  
3   89056700  
4   94639600

In [12]:
# 2.3.3

display(df.head(3), df.tail(3), df.shape, df.describe(), df.iloc[1:3], df[df["Open"] >= 180])


Date        Open        High         Low       Close   Adj Close  \
0  2021-09-27  145.470001  145.960007  143.820007  145.369995  143.707428   
1  2021-09-28  143.250000  144.750000  141.690002  141.910004  140.287018   
2  2021-09-29  142.470001  144.449997  142.029999  142.830002  141.196457   

      Volume  
0   74150700  
1  108972300  
2   74602000

Date        Open        High         Low       Close   Adj Close  \
248  2022-09-21  157.339996  158.740005  153.600006  153.720001  152.813461   
249  2022-09-22  152.380005  154.470001  150.910004  152.740005  151.839233   
250  2022-09-23  151.190002  151.470001  148.559998  150.429993  149.542831   

        Volume  
248  101696800  
249   86652500  
250   96029900

(251, 7)

Open        High         Low       Close   Adj Close  \
count  251.000000  251.000000  251.000000  251.000000  251.000000   
mean   158.428446  160.493387  156.568008  158.618048  157.251718   
std     12.505458   12.458429   12.381958   12.401045   12.270435   
min    130.070007  132.389999  129.039993  130.059998  129.113632   
25%    148.754998  149.904998  147.470001  148.845001  147.582604   
50%    159.589996  162.139999  156.720001  159.300003  157.972855   
75%    169.385002  171.065002  167.300003  169.060005  167.774918   
max    182.630005  182.940002  179.119995  182.009995  180.190964   

             Volume  
count  2.510000e+02  
mean   8.871277e+07  
std    2.625930e+07  
min    4.100000e+07  
25%    7.018920e+07  
50%    8.347440e+07  
75%    1.003336e+08  
max    1.954327e+08

Date        Open        High         Low       Close   Adj Close  \
1  2021-09-28  143.250000  144.750000  141.690002  141.910004  140.287018   
2  2021-09-29  142.470001  144.449997  142.029999  142.830002  141.196457   

      Volume  
1  108972300  
2   74602000

Date        Open        High         Low       Close   Adj Close  \
54  2021-12-13  181.119995  182.130005  175.529999  175.740005  173.983643   
64  2021-12-28  180.160004  181.330002  178.529999  179.289993  177.498154   
69  2022-01-04  182.630005  182.940002  179.119995  179.699997  177.904053   

       Volume  
54  153237000  
64   79144300  
69   99310400

In [11]:
# 3.3.2

display((arr := read_csv("https://raw.githubusercontent.com/akmand/datasets/master/iris.csv")).head(5))

arr[['sepal_length_cm']] = MinMaxScaler().fit_transform(arr[['sepal_length_cm']])
arr[['sepal_width_cm']] = StandardScaler().fit_transform(arr[['sepal_width_cm']])

arr.tail(5)


URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>